name: Run experiment for finding most frequently modified files

on:
  workflow_dispatch:
    inputs:
      topn:
        description: "The number of top frequently modified functions to return"
        type: number
        default: 10
      order:
        description: "The order to sort the functions by (asc or desc)"
        type: string
        default: "desc"
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        default: false
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      repos: "${{ steps.parse_repos.outputs.repos }}"
      topn: "${{ github.event.inputs.topn }}"
      order: "${{ github.event.inputs.order }}"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: |
          pip install -r requirements.txt

      - id: parse_repos
        run: |
          repos=$(python ${GITHUB_WORKSPACE}/.github/parse_repos.py)
          echo "repos=$repos" >> $GITHUB_OUTPUT
          echo "$repos"

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

  benchmark:
    needs:
      - setup
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        repo: ${{ fromJson(needs.setup.outputs.repos) }}
    steps:      
      - name: Checkout github repo (+ download lfs dependencies)
        uses: actions/checkout@v3
        with:
          lfs: true

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.repo.name }}
          ref: ${{ matrix.repo.sha }}
          path: "target_repo"

      - name: Find frequently modified functions
        run: |
          repo_name=${{ matrix.repo.name }}
          curr_dir=`pwd`
          outputdir="$curr_dir/results/${{ matrix.repo.language }}/$repo_name"
          mkdir -p $outputdir 
          python scripts/get_freq_chgd_fns.py \
            --path target_repo \
            --outputdir $outputdir \
            --topn ${{ needs.setup.outputs.topn }} \
            --language ${{ matrix.repo.language }}

      - name: Zip up results
        run: |
          zip -r results.zip results

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: results-${{ matrix.repo.name }}
          path: "results.zip"

  combine_output:
    name: Combine output from all benchmarks
    needs:
      - benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Download output zips
        uses: actions/download-artifact@v3

      - name: Combine output zips
        run: |
          mkdir results
          for zip in results-*/results.zip
          do
            unzip -oq $zip
          done
          zip -r results.zip results
      - name: Upload combined output files
        uses: actions/upload-artifact@v3
        with:
          name: results-all
          path: results.zip

  generate-report:
    needs:
      - combine_output
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Download artifacts for this run
        uses: actions/download-artifact@v3
        with:
          name: results-all
          path: results

      - name: Generate report
        run: |
          cd results
          unzip results.zip
          cd ..
          if [ -d baseline ]; then
            cd baseline
            unzip results.zip
            cd .. 
            python ${GITHUB_WORKSPACE}/src/benchmark/parse_reports.py --outputdir results/results --baselinedir baseline/results > $GITHUB_STEP_SUMMARY
          else
            python ${GITHUB_WORKSPACE}/src/benchmark/parse_reports.py --outputdir results/results > $GITHUB_STEP_SUMMARY
          fi